### ISSUE TITLE
Node.js.0.10.21\node.exe is not compatible with the version of Windows

### ISSUE THREAD

**Issue by amcdnl** [giggio/bower-nuget#10]
When I try to build I get the following:

2>  This version of \vmware-host\dev\myapp\pa
2>  ckages\Node.js.0.10.21\node.exe is not compatible with the version of Windows
2>   you're running. Check your computer's system information and then contact th
2>  e software publisher.
2>\vmware-host\dev\myapp\packages\Bower.js.1.
2>2.7.10\build\bower.js.targets(12,3): error MSB3073: The command ""\vmware-host
2>\dev\myapp\packages\Bower.js.1.2.7.10\build\
2>..\tools\npm.cmd" install bower --save-dev" exited with code 1.

**Comment by giggio** [comment]
This is a problem with the node.js package, not with bower-nuget. What version of Windows are you running? Looking at the message that seems to be the problem.

**Comment by amcdnl** [comment]
Windows 8.1

**Comment by giggio** [comment]
Weird... it works on mine.
Can you try to install only the node.js package and confirm if it works?

**Comment by barahilia** [comment]
Got precisely the same problem, just the error message was more informative:
`This version of ...\packages\Node.js.0.10.21\node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.`

And indeed, the computer, on which this happens, is **x86 (32 bit)**. While the same solution builds cleanly on x64 machines.

**Workaround**: install node.js directly from http://nodejs.org/ - it should automatically suggest the correct x86 installer, then replace `.\packages\Node.js.0.10.21\node.exe` with newly installed `C:\Program Files\nodejs\node.exe`.

I'll try to report it to node.js package maintainers.

**Comment by giggio** [comment]
Ok!
