### ISSUE TITLE
First build always fails.

### ISSUE THREAD

**Issue by grimurd** [giggio/bower-nuget#11]
The build on my build server always fails when trying to install bower packages. I'm using Visual Studio Online.

I have managed to reproduce this on my local machine, if i delete all scripts from the bower components folder and also delete bower from the node_modules folder and do a rebuild it will fail. However if i try to rebuild again it's successful. It's like this only happens the first time a build is performed and it has to install bower and also install bower packages.

This is the error i get on my build server:
RestoreBowerPkgs:
  Restoring Bower packages...
  "C:\a\src\src\packages\Bower.js.1.2.7.10\build..\tools\bower" install
C:\a\src\src\packages\Bower.js.1.2.7.10\build\bower.js.targets(17,3): error MSB3073: The command ""C:\a\src\src\packages\Bower.js.1.2.7.10\build..\tools\bower" install" exited with code 1. [C:\a\src\src\Project.Api\Project.Api.csproj]

Update: I think i have managed to reproduce this error, i created a public repo with the solution. It has similar structure as the project im currently working on with same .net version and latest versions of all nuget packages. It does not work if i try to build it. It however builds if i use bash to install the packages and then build. https://github.com/Sk1Zy/bowerjs-issue

**Comment by giggio** [comment]
I have not been paying much attention to this project as Microsoft is now going to support Bower on the whole ASP.NET pipeline.
But I would welcome a Pull Request. Would you like to help here?

**Comment by vmariano** [comment]
> I have not been paying much attention to this project as Microsoft is now going to support Bower on the whole ASP.NET pipeline. 

In which version? do you have an official notice of this?

**Comment by giggio** [comment]
@vmariano If you look at what is being done on ASP.NET 5 (ASP.NET vNext) and Visual Studio 2015, Bower is a first class citizen.

**Comment by grimurd** [comment]
I have moved away from using Visual Studio Online and this is not an issue anymore.
