### ISSUE TITLE
bower.json file in subdirectory of project.

### ISSUE THREAD

**Issue by paulvanbladel** [giggio/bower-nuget#12]
Hi,
Is it possible to have the .bowerrc and bower.json in a sub directory of the project, rather than the root?
Thx
paul.

**Comment by giggio** [comment]
Probably, but it not how it is used by everyone. Please fell free to submit a PR to solve the issue in a way that keeps it also working on the project root.

**Comment by paulvanbladel** [comment]
Never mind, I adopted in the mean time more mainstream habits :)
