### ISSUE TITLE
ENOGIT git is not installed or not in the PATH

### ISSUE THREAD

**Issue by dannief** [giggio/bower-nuget#13]
I get the following error after installing the package in nuget. Does this mean that we have to git installed externally? I was hoping to to not have any external dependencies. 

```
PM> bower install jquery --save
bower : bower jquery#*                  ENOGIT git is not installed or not in the PATH
At line:1 char:1
+ bower install jquery --save
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (bower jquery#* ...not in the PATH:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

_I had emailed the authers through the nuget.org website but just wanted to include the error here_

**Comment by giggio** [comment]
Yes, if you are using git packages, then you do have to have git installed.
