### ISSUE TITLE
What are the differences between Bower.js (this) and Bower nuget packages

### ISSUE THREAD

**Issue by techniq** [giggio/bower-nuget#5]
I noticed in NuGet there appears to be 2 similar bower packages, this one (`Bower.js`) and `Bower` by wayleee.  I can't find the source repo for `Bower` to look for myself.  It appears the `Bower` package was created first in November and this one in December, so I was curious if there were any improvements or differences that made you decide to create another one.

**Comment by giggio** [comment]
One of the main reason is that the `bower` package does not have a repo I could look into. I don't trust what I can't see. This package is much easier to make sense of, it is very simple, with few files.
Also, the `bower` package is much larger, as it packages the whole bower executables, while this one relies on the `npm.js` package (also mine) to install it's dependencies. It will also always install the latest bower.
If you don't want the latest bower you could use the `npm.js` package and npm directly to install whatever version you'd like.
Also, the `bower` package brings jsgit with it, which I didn't need.
And it places bower.cmd in you root folder. I don't like that either. That is why I update the path and place bower.cmd in a different directory, inside the packages directory.
I also added .targets files to allow bower install to run during the build.

**Comment by techniq** [comment]
Thanks for the response :).  I ended up just installing and using npm/bower directly, and setup Gulp to execute as part of my msbuild/visual studio build.
