### ISSUE TITLE
Tutorial to make it work in Visual Studio 2013

### ISSUE THREAD

**Issue by dsaf** [giggio/bower-nuget#7]
Tried following the instructions but it doesn't seem to be working:
[Visual Studio 2013, MVC 5]

PM> bower install ng-ckeditor --save

The term 'bower' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that th
e path is correct and try again.
At line:1 char:6
- bower <<<<  install ng-ckeditor --save
  - CategoryInfo          : ObjectNotFound: (bower:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

---

Thank you.

**Comment by giggio** [comment]
Did you ran it inside package manager console? If you don't have bower installed globally it will only work there.

**Comment by dsaf** [comment]
Yes, I ran it inside the Package Manager Console.

In case it matters, I don't have any of these installed: Git, Bower, Node, Gulp, Yeoman, Grunt.
I am running Windows 7.

I tried running '$env:path' in PMC and could see this entry:

"zzzzzzzzzz\packages\Bower.1.3.1\tools;"

Also I installed "Bower" not "Bower.js".

**Comment by giggio** [comment]
Oh, so this is not this repo. This is for "bower.js". Somebody else maintains the "bower" nuget. I don't think they have their project published on github...
